/**
 * Building on the sample skeleton for 'ui.fxml' COntroller Class generated by SceneBuilder 
 */
package comp3111.popnames;

import javafx.fxml.FXML;
import javafx.scene.control.RadioButton;
import javafx.scene.control.Button;
import javafx.scene.control.Tab;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleGroup;



public class Controller {

    @FXML
    private Tab tabTaskZero;

    @FXML
    private TextField textfieldNameF;

    @FXML
    private TextField textfieldYear;

    @FXML
    private Button buttonRankM;

    @FXML
    private TextField textfieldNameM;

    @FXML
    private Button buttonRankF;

    @FXML
    private Button buttonTopM;

    @FXML
    private Button buttonTopF;

    @FXML
    private Button buttonSummary;
    
    @FXML
    private Tab tabReport1;

    @FXML
    private ToggleGroup T1;

    @FXML
    private Tab tabReport2;

    @FXML
    private ToggleGroup T11;

    @FXML
    private Tab tabReport3;

    @FXML
    private ToggleGroup T111;

    @FXML
    private Tab tabApp1;

    @FXML
    private Tab tabApp2;

    @FXML
    private Tab tabApp3;

    @FXML
    private TextArea textAreaConsole;
    
    @FXML
    private Button buttonReport;
    
    @FXML
    private TextField textfieldtopN;
    
    @FXML
    private TextField textfieldy1;
    
    @FXML
    private TextField textfieldy2;
    
    @FXML
    private RadioButton male;
    
    @FXML
    private RadioButton female;
    
    
    
    /**
     *  Task Zero
     *  To be triggered by the "Summary" button on the Task Zero Tab 
     *  
     */
    @FXML
    void doSummary() {
    	int year = Integer.parseInt(textfieldYear.getText());
    	String oReport = AnalyzeNames.getSummary(year);
    	textAreaConsole.setText(oReport);
    }

  
    /**
     *  Task Zero
     *  To be triggered by the "Rank (female)" button on the Task Zero Tab
     *  
     */
    @FXML
    void doRankF() {
    	String oReport = "";
    	String iNameF = textfieldNameF.getText();
    	int iYear = Integer.parseInt(textfieldYear.getText());
    	int oRank = AnalyzeNames.getRank(iYear, iNameF, "F");
    	if (oRank == -1)
    		oReport = String.format("The name %s (female) has not been ranked in the year %d.\n", iNameF, iYear);
    	else
    		oReport = String.format("Rank of %s (female) in year %d is #%d.\n", iNameF, iYear, oRank);
    	textAreaConsole.setText(oReport);
    }

  
    /**
     *  Task Zero
     *  To be triggered by the "Rank (male)" button on the Task Zero Tab
     *  
     */
    @FXML
    void doRankM() {
    	String oReport = "";
    	String iNameM = textfieldNameM.getText();
    	int iYear = Integer.parseInt(textfieldYear.getText());
    	int oRank = AnalyzeNames.getRank(iYear, iNameM, "M");
    	if (oRank == -1)
    		oReport = String.format("The name %s (male) has not been ranked in the year %d.\n", iNameM, iYear);
    	else
    		oReport = String.format("Rank of %s (male) in year %d is #%d.\n", iNameM, iYear, oRank);
    	textAreaConsole.setText(oReport);
    }


    /**
     *  Task Zero
     *  To be triggered by the "Top 5 (female)" button on the Task Zero Tab
     *  
     */
    @FXML
    void doTopF() {
    	String oReport = "";
    	final int topN = 5;
    	int iYear = Integer.parseInt(textfieldYear.getText());
    	oReport = String.format("Top %d most popular names (female) in the year %d:\n", topN, iYear);
    	for (int i=1; i<=topN; i++)
    		oReport += String.format("#%d: %s\n", i, AnalyzeNames.getName(iYear, i, "F"));
    	textAreaConsole.setText(oReport);
    }


    /**
     *  Task Zero
     *  To be triggered by the "Top 5 (male)" button on the Task Zero Tab
     *  
     */
    @FXML
    void doTopM() {
    	String oReport = "";
    	final int topN = 5;
    	int iYear = Integer.parseInt(textfieldYear.getText());
    	oReport = String.format("Top %d most popular names (male) in the year %d:\n", topN, iYear);
    	for (int i=1; i<=topN; i++)
    		oReport += String.format("#%d: %s\n", i, AnalyzeNames.getName(iYear, i, "M"));
    	textAreaConsole.setText(oReport);
    }
    
    /**
	 * Task One 
	 * 
	 */
	
    @FXML
	void doReport() {
    	
    	String oReport = "";
    	int n = Integer.parseInt(textfieldtopN.getText());
    	int y1 = Integer.parseInt(textfieldy1.getText());
    	int y2 = Integer.parseInt(textfieldy2.getText());
    	String[] arr = new String[y2-y1+1];
    	textAreaConsole.setStyle("-fx-font-family: monospace");
		
    	
    	//invalid input
    	if(Integer.parseInt(textfieldtopN.getText())<1) {
    		oReport += "Please input a number that is greater than or equal to 1 for the value N\n";
    	}
    	if(Integer.parseInt(textfieldy1.getText())<1880||Integer.parseInt(textfieldy2.getText())>2019) {
    		oReport += "The period of interest must be between 1880 and 2019\n";
    	}
    	
    	//valid input
    	if(male.isSelected()&&n>=1&&y1>=1880&&y2<=2019) {
    		
	    	for(int i=0; i<=y2-y1; i++)
	    		arr[i] = AnalyzeNames.getName(i+y1, 1, "M");
	    	String topname = AnalyzeNames.FrequentWordname(arr);
	    	int topnum = AnalyzeNames.FrequentWordnum(arr);
	
	    	oReport = String.format("Year\t");
	    	for (int k=1; k<=n; k++)
	    			oReport += String.format("Top%d\t\t", k);
	    	oReport += String.format("\n");
	    	
	    	for (int i=y1; i<=y2; i++) {
	    		oReport += String.format("%d\t", i);
	    		for (int j=1; j<=n; j++) {
	    			String name = AnalyzeNames.getName(i, j, "M");
	    			if (name.length()>7)
	    				oReport += String.format("%s\t", name);
	    			else
	    				oReport += String.format("%s\t\t", name);
	    		}
	    		oReport += String.format("\n");
	    	}
	    	
	
	    	oReport += String.format("\nOver the period %d to %d, %s for Male has hold the top spot \nmost often for a total of %d times.", y1, y2, topname, topnum);
	    	
	    	
		}
		
    	if(female.isSelected()&&n>=1&&y1>=1880&&y2<=2019) {
			
	    	for(int i=0; i<=y2-y1; i++)
	    		arr[i] = AnalyzeNames.getName(i+y1, 1, "F");
	    	String topname = AnalyzeNames.FrequentWordname(arr);
	    	int topnum = AnalyzeNames.FrequentWordnum(arr);
	
	    	oReport = String.format("Year\t");
	    	for (int k=1; k<=n; k++)
	    			oReport += String.format("Top%d\t\t", k);
	    	oReport += String.format("\n");
	    	
	    	for (int i=y1; i<=y2; i++) {
	    		oReport += String.format("%d\t", i);
	    		for (int j=1; j<=n; j++) {
	    			String name = AnalyzeNames.getName(i, j, "F");
	    			if (name.length()>7)
	    				oReport += String.format("%s\t", name);
	    			else
	    				oReport += String.format("%s\t\t", name);
	    		}
	    		oReport += String.format("\n");
	    	}
	    	
	
	    	oReport += String.format("\nOver the period %d to %d, %s for Female has hold the top spot \nmost often for a total of %d times.", y1, y2, topname, topnum);
	    	
	    	
		}
    	textAreaConsole.setText(oReport);
		
	}
	
	
}


	